// Generated by CoffeeScript 2.7.0
(function() {
  var Q, isPromise, l, tryCb, tryResolv;

  l = require("gqcolorlog").logging;

  Q = require('q');

  this.gqcb = {};

  isPromise = function(value) {
    return value !== null && typeof value === 'object' && typeof value.then === 'function';
  };

  tryCb = function(e, r, next) {
    if (e) {
      l.error(e);
      l.filterederror(e);
    }
    if (next) {
      next(e, r);
    }
    return r;
  };

  tryResolv = function(e, r, def) {
    var deferred;
    deferred = def || Q.defer();
    if (e) {
      deferred.reject(e);
    } else {
      deferred.resolve(r);
    }
    return deferred.promise;
  };

  this.gqcb.tryCb = tryCb;

  this.gqcb.tryResolv = tryResolv;

  this.gqcb.cb = function(e, r, next, def) {
    if (isPromise(this.this)) {
      return tryResolv(e, r, def);
    } else {
      return tryCb(e, r, next);
    }
  };

}).call(this);
